### ISSUE TITLE
sdk-java v4.1.1 throws mockito exception while creating VisualRegressionTracker object

### ISSUE THREAD

**Issue by shankybnl** [Visual-Regression-Tracker/Visual-Regression-Tracker#141]
Hi,

First of all, thank you for the great tool. I came across below exception while initializing VisualRegressionTracker (VisualRegressionTracker(config)). But this has been fixed after adding mockito-core library. I wanted to check if it is a known required dependency and mentioned anywhere in the documentation.

```
java.lang.ExceptionInInitializerError
	at qa.wm.utils.ComLib.oneTimeSetUp(ComLib.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:327)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: interface org.slf4j.Logger.

Mockito can only mock non-private & non-final classes.
```

Mockito library:

```
<!-- https://mvnrepository.com/artifact/org.mockito/mockito-core -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>2.22.0</version>
			<scope>test</scope>
		</dependency>
```

**Comment by pashidlos** [comment]
hi @shankybnl 

if I'm not mistaken similar issue was fixed in `4.3.1`
could you try upgrading it?
also, please, specify the versions you are using in `docker-compose.yml`

thank you for creating a ticket!

**Comment by pashidlos** [comment]
if it's still the issue, could you try reproducing it with any of example projects?
https://github.com/Visual-Regression-Tracker/examples-java

**Comment by shankybnl** [comment]
@pashidlos Thank you for the prompt response. I have tried running tests with sdk-java v4.3.1 and it worked fine without mockito dependency.

**Comment by shankybnl** [comment]
@pashidlos You might want to remove "waiting" label from this issue now  :)
