### ISSUE TITLE
Unclear error when IMG_UPLOAD_FOLDER env value is missing

### ISSUE THREAD

**Issue by wasder** [Visual-Regression-Tracker/Visual-Regression-Tracker#153]
When IMG_UPLOAD_FOLDER enviroment doesn't present, there is an error on POST /test-runs 

```
{
  "path": "/test-runs",
  "name": "TypeError",
  "message": "The \"path\" argument must be of type string. Received undefined",
  "exception": {
    "code": "ERR_INVALID_ARG_TYPE"
  },
  "stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received undefined\n    at validateString (internal/validators.js:120:11)\n    at Object.resolve (path.js:980:7)\n    at StaticService.ensureDirectoryExistence (/dist/shared/static/static.service.js:60:41)\n    at StaticService.getImagePath (/dist/shared/static/static.service.js:56:14)\n    at StaticService.saveImage (/dist/shared/static/static.service.js:27:33)\n    at TestRunsService.create (/dist/test-runs/test-runs.service.js:174:46)\n    at TestRunsService.postTestRun (/dist/test-runs/test-runs.service.js:56:36)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async /node_modules/@nestjs/core/router/router-execution-context.js:46:28"
}
```

It's unclear by the text of the error what is wrong. Should check for env existence first.

**Comment by pashidlos** [comment]
env param is gonna be removed in `4.7.0` release in scope of 
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/160
