### ISSUE TITLE
[BUG] "Unique constraint"-error on paraller run

### ISSUE THREAD

**Issue by frezot** [Visual-Regression-Tracker/Visual-Regression-Tracker#258]
**Steps**:
- create couple specs with tests
- in each use `PlaywrightVisualRegressionTracker` at `beforeAll` section
- run test in parallel by jest (e.g. `yarn jest  --maxWorkers=4`)

**Expected**: correct execution in all threads

**Actual**: first tests in spec-files got error
```
Error: {
  "path": "/builds",
  "name": "Error",
  "message": "\nInvalid `prisma.build.create()` invocation:\n\n\n  Unique constraint failed on the fields: (`projectId`,`ciBuildId`)",
  "exception": {
    "code": "P2002",
    "clientVersion": "2.12.1",
    "meta": {
      "target": [
        "projectId",
        "ciBuildId"
      ]
    }
  },
  "stack": "Error: \nInvalid `prisma.build.create()` invocation:\n\n\n  Unique constraint failed on the fields: (`projectId`,`ciBuildId`)\n    at PrismaClientFetcher.request (/node_modules/@prisma/client/runtime/index.js:79355:15)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
}
```

**Comment by frezot** [comment]
Bug still reproduced 😓
For example at 4.17.0

**Comment by pashidlos** [comment]
@frezot could you share stack-trace?

**Comment by frezot** [comment]
[vrt-api.log](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/files/7253027/vrt-api.log)

**Comment by pashidlos** [comment]
```
[Nest] 18   - 09/29/2021, 3:04:37 PM   Object:
{
  "code": "P2002",
  "clientVersion": "2.12.1",
  "meta": {
    "target": [
      "projectId",
      "ciBuildId"
    ]
  }
}
 +32477ms
Error: 
Invalid `prisma.build.upsert()` invocation:

  Unique constraint failed on the fields: (`projectId`,`ciBuildId`)
    at PrismaClientFetcher.request (/node_modules/@prisma/client/runtime/index.js:79355:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by pashidlos** [comment]
@frezot unfortunately the issue is on Prisma side https://github.com/prisma/prisma/issues/3242
for now it's possible to workaround only by wrapping code to start build in try-catch block and re-try again
