### ISSUE TITLE
Network connection lost when sending a request POST /test-runs

### ISSUE THREAD

**Issue by nGervasyuk** [Visual-Regression-Tracker/Visual-Regression-Tracker#377]
Reproduced periodically, during the tests execution on all environments.

```
api_1        | [Nest] 18  - 09/16/2022, 5:17:57 AM   ERROR [UnauthorizedException: Unauthorized
api_1        |     at JwtAuthGuard.handleRequest (/node_modules/@nestjs/passport/dist/auth.guard.js:68:30)
api_1        |     at /node_modules/@nestjs/passport/dist/auth.guard.js:49:128
api_1        |     at /node_modules/@nestjs/passport/dist/auth.guard.js:91:24
api_1        |     at allFailed (/node_modules/passport/lib/middleware/authenticate.js:110:18)
api_1        |     at attempt (/node_modules/passport/lib/middleware/authenticate.js:183:28)
api_1        |     at JwtStrategy.strategy.fail (/node_modules/passport/lib/middleware/authenticate.js:305:9)
api_1        |     at JwtStrategy.authenticate (/node_modules/passport-jwt/lib/strategy.js:96:21)
api_1        |     at attempt (/node_modules/passport/lib/middleware/authenticate.js:369:16)
api_1        |     at authenticate (/node_modules/passport/lib/middleware/authenticate.js:370:7)
api_1        |     at /node_modules/@nestjs/passport/dist/auth.guard.js:96:3] UnauthorizedException: Unauthorized
postgres_1   | 2022-09-16 05:29:41.755 UTC [40501] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
```

**Comment by pashidlos** [comment]
the error is saying request doesn't have auth headers 
is there any steps to reproduce this?
